CREATE table "CLIENTE" (
    "CPF"        VARCHAR2(14) NOT NULL,
    "NOME"       VARCHAR2(30) NOT NULL,
    "EMAIL"      VARCHAR2(30),
    "PONTOS_CRM" NUMBER,
    "RUA"        VARCHAR2(30),
    "NUM"        VARCHAR2(6),
    "BAIRRO"     VARCHAR2(20),
    "CIDADE"     VARCHAR2(20),
    "ESTADO"     VARCHAR2(20),
    constraint  "CLIENTE_PK" primary key ("CPF")
)
/

CREATE table "TELEFONE_CLIENTE" (
    "CPF"        VARCHAR2(14) NOT NULL,
    "NUMERO"     VARCHAR2(20) NOT NULL
)
/

alter table "TELEFONE_CLIENTE" add constraint  "TELEFONE_CLIENTE_PK" primary key ("CPF","NUMERO")
/

ALTER TABLE "TELEFONE_CLIENTE" ADD CONSTRAINT "TELEFONE_CLIENTE_FK" 
FOREIGN KEY ("CPF")
REFERENCES "CLIENTE" ("CPF")
ON DELETE CASCADE

/

CREATE table "FILIAL" (
    "CODIGO_IDENTIFICACAO" NUMBER NOT NULL,
    "NOME"                 VARCHAR2(30),
    "ENDERECO"             VARCHAR2(50),
    "TELEFONE"             VARCHAR2(20),
    constraint  "FILIAL_PK" primary key ("CODIGO_IDENTIFICACAO")
)
/

CREATE table "REALIZA_RECLAMACAO" (
    "CPF"                  VARCHAR2(14) NOT NULL,
    "CODIGO_IDENTIFICACAO" NUMBER NOT NULL,
    "DATA_E_HORA"          TIMESTAMP,
    "DESCRICAO"            VARCHAR2(100)
)
/

alter table "REALIZA_RECLAMACAO" add constraint  "REALIZA_RECLAMACAO_PK" primary key ("CPF","CODIGO_IDENTIFICACAO")
/

ALTER TABLE "REALIZA_RECLAMACAO" ADD CONSTRAINT "REALIZA_RECLAMACAO_FILIAL_FK" 
FOREIGN KEY ("CODIGO_IDENTIFICACAO")
REFERENCES "FILIAL" ("CODIGO_IDENTIFICACAO")

/
ALTER TABLE "REALIZA_RECLAMACAO" ADD CONSTRAINT "REALIZA_RECLAMACAO_CLIENTE_FK" 
FOREIGN KEY ("CPF")
REFERENCES "CLIENTE" ("CPF")

/

CREATE table "FUNCIONARIO" (
    "MATRICULA"      VARCHAR2(10) NOT NULL,
    "CPF"            VARCHAR2(14) NOT NULL,
    "IDENTIDADE"     VARCHAR2(10),
    "NOME"           VARCHAR2(30) NOT NULL,
    "ENDERECO"       VARCHAR2(50),
    "SALARIO"        NUMBER,
    "FUNCAO"         VARCHAR2(15),
    "CODIGO_FILIAL"  NUMBER,
    "MAT_SUPERVISOR" VARCHAR2(10),
    constraint  "FUNCIONARIO_PK" primary key ("MATRICULA")
)
/

ALTER TABLE "FUNCIONARIO" ADD CONSTRAINT "CODIGO_FILIAL_FK" 
FOREIGN KEY ("CODIGO_FILIAL")
REFERENCES "FILIAL" ("CODIGO_IDENTIFICACAO")

/
alter table "FUNCIONARIO" add
constraint "FUNC_FUNCOES" 
check (FUNCAO IN ('caixa', 'empacotador', 'açougueiro', 'padeiro', 'limpeza','segurança'))
/   

CREATE table "TELEFONE_FUNCIONARIO" (
    "MATRICULA"  VARCHAR2(10) NOT NULL,
    "NUMERO"     VARCHAR2(20) NOT NULL
)
/

alter table "TELEFONE_FUNCIONARIO" add constraint  "TELEFONE_FUNCIONARIO_PK" primary key ("MATRICULA","NUMERO")
/

ALTER TABLE "TELEFONE_FUNCIONARIO" ADD CONSTRAINT "TELEFONE_FUNCIONARIO_FK" 
FOREIGN KEY ("MATRICULA")
REFERENCES "FUNCIONARIO" ("MATRICULA")
ON DELETE CASCADE

/

CREATE table "DEPENDENTE" (
    "MATRICULA"       VARCHAR2(10) NOT NULL,
    "CPF_DEPENDENTE"  VARCHAR2(14) NOT NULL,
    "DATA_NASCIMENTO" DATE,
    "NOME"            VARCHAR2(30) NOT NULL
)
/

alter table "DEPENDENTE" add constraint  "DEPENDENTE_PK" primary key ("MATRICULA","CPF_DEPENDENTE")
/

ALTER TABLE "DEPENDENTE" ADD CONSTRAINT "DEPENDENTE_FK" 
FOREIGN KEY ("MATRICULA")
REFERENCES "FUNCIONARIO" ("MATRICULA")
ON DELETE CASCADE

/
CREATE table "CATEGORIA" (
   "IDENTIFICADOR" NUMBER NOT NULL,
   "NOME"          VARCHAR2(30),
   constraint  "CATEGORIA_PK" primary key ("IDENTIFICADOR")
)
/
CREATE table "MARCA" (
    "IDENTIFICADOR" NUMBER,
    "NOME" VARCHAR2(30),
    constraint  "MARCA_PK" primary key ("IDENTIFICADOR")
)
/

CREATE table "PRODUTO" (
    "CODIGO_IDENTIFICACAO" NUMBER NOT NULL,
    "NOME"                 VARCHAR2(30) NOT NULL,
    "DESCRICAO"            VARCHAR2(50),
    "MARGEM_LUCRO_MIN"     NUMBER,
    "CATEGORIA"            NUMBER,
    "FILIAL"               NUMBER,
    "QUANTIDADE"           NUMBER,
    "DATA_VALIDADE"        DATE,
    "PRECO_COMPRA"         NUMBER,
    "PRECO_VENDA"          NUMBER,
    "DATA_COMPRA"          DATE,
    "MARCA"                NUMBER,
    constraint  "PRODUTO_PK" primary key ("CODIGO_IDENTIFICACAO")
)
/

ALTER TABLE "PRODUTO" ADD CONSTRAINT "PRODUTO_FILIAL_FK"
FOREIGN KEY ("FILIAL")
REFERENCES "FILIAL" ("CODIGO_IDENTIFICACAO")
ON DELETE SET NULL

/
ALTER TABLE "PRODUTO" ADD CONSTRAINT "PRODUTO_CATEGORIA_FK"
FOREIGN KEY ("CATEGORIA")
REFERENCES "CATEGORIA" ("IDENTIFICADOR")
ON DELETE SET NULL

/
alter table "PRODUTO" add
constraint "CHECK_QUANTIDADE_PRODUTO"
check (QUANTIDADE >= 0)
/
ALTER TABLE "PRODUTO" ADD CONSTRAINT "MARCA_FK"
FOREIGN KEY ("MARCA")
REFERENCES "MARCA" ("IDENTIFICADOR")
/
CREATE table "CAIXA" (
    "NUMERO_CAIXA" NUMBER NOT NULL,
    "FILIAL"       NUMBER,
    constraint  "CAIXA_PK" primary key ("NUMERO_CAIXA")
)
/

ALTER TABLE "CAIXA" ADD CONSTRAINT "CAIXA_FILIAL_FK" 
FOREIGN KEY ("FILIAL")
REFERENCES "FILIAL" ("CODIGO_IDENTIFICACAO")
ON DELETE CASCADE

/

CREATE table "EQUIPAMENTO" (
    "IDENTIFICADOR" NUMBER NOT NULL,
    "DESCRICAO"     VARCHAR2(50),
    "CAIXA"         NUMBER,
    constraint  "EQUIPAMENTO_PK" primary key ("IDENTIFICADOR")
)
/

ALTER TABLE "EQUIPAMENTO" ADD CONSTRAINT "EQUIPAMENTO_CAIXA_FK"
FOREIGN KEY ("CAIXA")
REFERENCES "CAIXA" ("NUMERO_CAIXA")
ON DELETE SET NULL

/

CREATE table "REALIZA_MANUTENCAO" (
    "IDENTIFICADOR_EQUIPAMENTO" NUMBER,
    "MATRICULA_FUNCIONARIO"     VARCHAR2(10),
    "DATA_HORA"                 TIMESTAMP,
    "CUSTO"                     NUMBER
)
/

alter table "REALIZA_MANUTENCAO" add constraint  "REALIZA_MANUTENCAO_PK" primary key ("IDENTIFICADOR_EQUIPAMENTO","MATRICULA_FUNCIONARIO")
/

ALTER TABLE "REALIZA_MANUTENCAO" ADD CONSTRAINT "REALIZA_MANUTENCAO_EQUIPAMENTO_FK"
FOREIGN KEY ("IDENTIFICADOR_EQUIPAMENTO")
REFERENCES "EQUIPAMENTO" ("IDENTIFICADOR")
ON DELETE CASCADE

/
ALTER TABLE "REALIZA_MANUTENCAO" ADD CONSTRAINT "REALIZA_MANUTENCAO_FUNCIONARIO_FK"
FOREIGN KEY ("MATRICULA_FUNCIONARIO")
REFERENCES "FUNCIONARIO" ("MATRICULA")
ON DELETE CASCADE

/
CREATE table "ORDEM_DE_COMPRA" (
    "NUMERO_NOTA_FISCAL" NUMBER NOT NULL,
    "DATA_E_HORA_VENDA" DATE,
    "NUMERO_DO_CAIXA" NUMBER,
    "CLIENTE" VARCHAR2(14),
    "FILIAL" NUMBER,
    "FUNCIONARIO" VARCHAR2(10),
    constraint  "ORDEM_DE_COMPRA_PK" primary key ("NUMERO_NOTA_FISCAL")
)
/
ALTER TABLE "ORDEM_DE_COMPRA" ADD CONSTRAINT "CAIXA_FK"
FOREIGN KEY ("NUMERO_DO_CAIXA")
REFERENCES "CAIXA" ("NUMERO_CAIXA")
ON DELETE CASCADE

/
ALTER TABLE "ORDEM_DE_COMPRA" ADD CONSTRAINT "CLIENTE_FK"
FOREIGN KEY ("CLIENTE")
REFERENCES "CLIENTE" ("CPF")
ON DELETE CASCADE

/
/
ALTER TABLE "ORDEM_DE_COMPRA" ADD CONSTRAINT "FILIAL_FK"
FOREIGN KEY ("FILIAL")
REFERENCES "FILIAL" ("CODIGO_IDENTIFICACAO")
ON DELETE CASCADE

/
/
ALTER TABLE "ORDEM_DE_COMPRA" ADD CONSTRAINT "FUNCIONARIO_FK"
FOREIGN KEY ("FUNCIONARIO")
REFERENCES "FUNCIONARIO" ("MATRICULA")
ON DELETE CASCADE

/

CREATE table "ITEM" (
    "INDENTIFICADOR" NUMBER NOT NULL,
    "QUANTIDADE" NUMBER,
    "PRECO_DO_PRODUTO" NUMBER,
    "DESCONTO" NUMBER,
    constraint  "ITEM_PK" primary key ("INDENTIFICADOR")
)
/