CREATE table "CLIENTE" (
    "CPF"        VARCHAR2(14) NOT NULL,
    "NOME"       VARCHAR2(30) NOT NULL,
    "EMAIL"      VARCHAR2(30),
    "PONTOS_CRM" NUMBER,
    "RUA"        VARCHAR2(30),
    "NUM"        VARCHAR2(6),
    "BAIRRO"     VARCHAR2(20),
    "CIDADE"     VARCHAR2(20),
    "ESTADO"     VARCHAR2(20),
    constraint  "CLIENTE_PK" primary key ("CPF")
)
/

CREATE table "TELEFONE_CLIENTE" (
    "CPF"        VARCHAR2(14) NOT NULL,
    "NUMERO"     VARCHAR2(20) NOT NULL
)
/

alter table "TELEFONE_CLIENTE" add constraint  "TELEFONE_CLIENTE_PK" primary key ("CPF","NUMERO")
/

ALTER TABLE "TELEFONE_CLIENTE" ADD CONSTRAINT "TELEFONE_CLIENTE_FK" 
FOREIGN KEY ("CPF")
REFERENCES "CLIENTE" ("CPF")
ON DELETE CASCADE

/

CREATE table "FILIAL" (
    "CODIGO_IDENTIFICACAO" NUMBER NOT NULL,
    "NOME"                 VARCHAR2(30),
    "ENDERECO"             VARCHAR2(50),
    "TELEFONE"             VARCHAR2(20),
    constraint  "FILIAL_PK" primary key ("CODIGO_IDENTIFICACAO")
)
/

CREATE table "REALIZA_RECLAMACAO" (
    "CPF"                  VARCHAR2(14) NOT NULL,
    "CODIGO_IDENTIFICACAO" NUMBER NOT NULL,
    "DATA_E_HORA"          TIMESTAMP,
    "DESCRICAO"            VARCHAR2(100)
)
/

alter table "REALIZA_RECLAMACAO" add constraint  "REALIZA_RECLAMACAO_PK" primary key ("CPF","CODIGO_IDENTIFICACAO")
/

ALTER TABLE "REALIZA_RECLAMACAO" ADD CONSTRAINT "REALIZA_RECLAMACAO_FILIAL_FK" 
FOREIGN KEY ("CODIGO_IDENTIFICACAO")
REFERENCES "FILIAL" ("CODIGO_IDENTIFICACAO")

/
ALTER TABLE "REALIZA_RECLAMACAO" ADD CONSTRAINT "REALIZA_RECLAMACAO_CLIENTE_FK" 
FOREIGN KEY ("CPF")
REFERENCES "CLIENTE" ("CPF")

/

CREATE table "FUNCIONARIO" (
    "MATRICULA"      VARCHAR2(10) NOT NULL,
    "CPF"            VARCHAR2(14) NOT NULL,
    "IDENTIDADE"     VARCHAR2(10),
    "NOME"           VARCHAR2(30) NOT NULL,
    "ENDERECO"       VARCHAR2(50),
    "SALARIO"        NUMBER,
    "FUNCAO"         VARCHAR2(15),
    "CODIGO_FILIAL"  NUMBER,
    "MAT_SUPERVISOR" VARCHAR2(10),
    constraint  "FUNCIONARIO_PK" primary key ("MATRICULA")
)
/

ALTER TABLE "FUNCIONARIO" ADD CONSTRAINT "CODIGO_FILIAL_FK" 
FOREIGN KEY ("CODIGO_FILIAL")
REFERENCES "FILIAL" ("CODIGO_IDENTIFICACAO")

/
alter table "FUNCIONARIO" add
constraint "FUNC_FUNCOES" 
check (FUNCAO IN ('caixa', 'empacotador', 'açougueiro', 'padeiro', 'limpeza','segurança'))
/   

CREATE table "TELEFONE_FUNCIONARIO" (
    "MATRICULA"  VARCHAR2(10) NOT NULL,
    "NUMERO"     VARCHAR2(20) NOT NULL
)
/

alter table "TELEFONE_FUNCIONARIO" add constraint  "TELEFONE_FUNCIONARIO_PK" primary key ("MATRICULA","NUMERO")
/

ALTER TABLE "TELEFONE_FUNCIONARIO" ADD CONSTRAINT "TELEFONE_FUNCIONARIO_FK" 
FOREIGN KEY ("MATRICULA")
REFERENCES "FUNCIONARIO" ("MATRICULA")
ON DELETE CASCADE

/

CREATE table "DEPENDENTE" (
    "MATRICULA"       VARCHAR2(10) NOT NULL,
    "CPF_DEPENDENTE"  VARCHAR2(14) NOT NULL,
    "DATA_NASCIMENTO" DATE,
    "NOME"            VARCHAR2(30) NOT NULL
)
/

alter table "DEPENDENTE" add constraint  "DEPENDENTE_PK" primary key ("MATRICULA","CPF_DEPENDENTE")
/

ALTER TABLE "DEPENDENTE" ADD CONSTRAINT "DEPENDENTE_FK" 
FOREIGN KEY ("MATRICULA")
REFERENCES "FUNCIONARIO" ("MATRICULA")
ON DELETE CASCADE

/


